### PR TITLE
Refactor `read_resource()`

### LINKED ISSUE #210: Make `read_resource()` more modular
`read_resource()` is very long. It could benefit from a more modular approach.

### ✅ Get resource, includes check_package()

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L202-L204

- [x] Already a helper function

### ✅ Get paths, schema and fields

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L205-L210

- [x] Not much gain here

### ✅ Check all selected columns appear in schema

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L211-L222

- [x] Typical check, not much gain here

### ❌ Create locale with encoding, decimal_mark and grouping_mark

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L223-L262

- [x] Needs helper function `get_encoding()` (or `encoding()`)
- [x] Needs `resource$encoding` and `resource$fields`, so best to pass `resource` (and `package`)
- [x] Returns `readr::locale`

### ❌ Create col_types: list(<collector_character>, <collector_logical>, ...)

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L263-L327

What we want is:

```
cols(
  field1 = col_integer(),
  field2 = col_character(),
  ...
)
```

- [x] Helper function `get_cols()` (or `cols()`). It could work on a single field, but more useful is that it always returns a `readr::cols()`
- [x] It then also aligns with a future `get_na_cols()` (or `na_cols()`) cf. https://kylehusmann.com/interlacer/reference/na_cols.html
- [x] Maybe internally it also has a function `get_col_type()` (or `col()`) for a single field (so `get_cols()` is mostly a wrapper).
- [x] Do we need a helper function per column type? Would likely improve readability if just have a switch on field type that then correctly passes the field to the correct function?

So:

```R
get_cols <- function(fields) {
  for field:
    get_col(field)
}

get_col <- function(field) {
  type <-
  switch(type,
    "string" = col_string(),
    "number" = col_number(),
    ...
  )
}

col_string <- function() ...
col_number <- function(field) {
  get_enum()
  get_bare_number()
  get_format()
  ...
} 
```

### ❌ Assign names: list("name1" = <collector_character>, "name2" = ...)

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L328-L330

- [x] This should be integrated in `get_cols()`

### ✅ Select CSV dialect, see https://specs.frictionlessdata.io/csv-dialect/

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L331-L334

- [x] Not much gain here

### ✅ Read data directly

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L335-L338

- [x] Not much gain here

### ✅ Read data from data

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L339-L342

- [x] Not much gain here

### ❌ Read data from path(s)

https://github.com/frictionlessdata/frictionless-r/blob/72b86941a15f84b1ca1416e2c4d48ee73d3fd3ff/R/read_resource.R#L343-L379

Is a for loop over paths, calling `readr::read_delim()` for all and then `dplyr::bind_rows()`

- [x] Maybe we can have a `read_delim()` that calls all the `get_cols()` internally rather than building it `encoding` and `cols` and `na_cols` beforehand? But maybe that is harder to debug?

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR fixes #210 by refactoring `read_resource()`. It uses several helper functions placed in `utils.R`.

The PR adds the helper functions here below. Comments describe the differences between the description of @peterdesmet in #210 and the actual implementation:
- [x] `get_encoding()`. Used in `create_local()` (see below)
- [x] `create_locale()`. It needs `resource$encoding` and `resource$fields`. I didn't pass `resource` (and `package`) as I didn't see the advantage. It doesn't decrease the number of arguments and it makes the helper function `get_encoding()` longer: we need to call `get_schema()` in the function again.
- [x] `create_col_types()` (wrapper) and `create_col_type()` instead of the proposed `get_cols()` and `get_col()`. I find the verb `get` in the function name a little misleading: the functions are creating col types for the resource to read, not getting them from the resource.
- [x] `col_integer()`, `col_number()`, `col_string()`, `col_date()`, `col_time()`, `col_datetime()`, used in `switch()` in `create_col_type()`. It follows the specs in #210. 
- [x] ~`read_from_paths()` (wrapper) and~ `read_from_path()`: using a `map_df()` simplify extremely the code. 

We could eventually move the helper functions created in this PR in an apart utility file, maybe `utils-resource.R`.

No addition to `NEWS.md` as it doesn't affect the user experience. But we could add it if wished.

### CODE REVIEW

**Comment by damianooldoni** [comment]
Some errors while checking: convert to draft.

**Comment by peterdesmet** [comment]
Please create:

- `get_encoding.R`
- `create_locale.R`
- `create_col_types.R`
- `col_types.R`
- `read_from_path.R`

**Review by peterdesmet — APPROVED** [review]
Thanks for this @damianooldoni. I have refactored further:

- `read_from_path()` now contains the `map_df()`, so we only have to pass three arguments: `package`, `resource_name`, `col_select`. All checks are done there, so `read_resource()` got really small 👍 
- Renamed `create_col_types()` to `cols()` and placed it in `col_types.R` (cf. readr)
- Renamed `create_col_type()` to `field_to_col()` and placed in `col_types.R` as well. It uses the argument `field` rather than `x`
- Renamed `create_locale()` to `locale()` (cf. readr)
- `col_` functions are placed in `collectors.R` (cf. readr)
- Updated some argument descriptions and function families

**Comment by damianooldoni** [comment]
Well done, @peterdesmet!

**Pull request merged**
